export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import Navbar from "../(app)/navbar/page"
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <div>
        {<Navbar/>}
        {children}
      </div>
  )
}
