export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import Navbar from "../(app)/navbar/Navbar"
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <body>
        {<Navbar/>}
        {children}
        </body>
  )
}
